runner:
  total_steps: 10000
  gradient_clipping: 1.0
  gradient_accumulate_steps: 1

  log_step: 1000
  eval_step: 1000
  save_step: 1000
  max_keep: 100
  eval_dataloaders:
    - dev
  test_dataloaders:
    - test

optimizer:
  name: AdamW
  lr: 1.e-3


downstream_expert:
  datarc:
    num_speakers: 1
    rate: 16000
    src: ['noisy']
    tgt: ['clean']
    n_fft: 512
    win_length: 400
    hop_length: 160
    window: "hann"
    center: True

  loaderrc:
    num_workers: 0
    train_batch_size: 8
    eval_batch_size: 1
    train_dir: ./downstream/enhancement_stft2/datasets/voicebank/wav16k/train
    dev_dir: ./downstream/enhancement_stft2/datasets/voicebank/wav16k/dev
    test_dir: ./downstream/enhancement_stft2/datasets/voicebank/wav16k/test
  
  modelrc: 
    model: SepRNN
    rnn: LSTM
    rnn_layers: 3
    hidden_size: 256
    dropout: 0.1
    non_linear: sigmoid
    bidirectional: True
    loss_type: L1
    mask_type: AM
    log: log1p