# this voxceleb1 is doing speaker classification task!
runner:
  total_steps: 20000
  gradient_clipping: 1
  gradient_accumulate_steps: 4

  log_step: 2000
  eval_step: 2000
  save_step: 2000
  max_keep: 1
  eval_dataloaders: 
    - dev
  test_dataloaders: 
    - test
  
optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-3

downstream_expert: 
  datarc:
    file_path: /path/to/VoxCeleb1
    meta_data: downstream/voxceleb1/mini_veri_test_class.txt
    num_workers: 12
    train_batch_size: 8
    eval_batch_size: 1
    max_timestep: 128000

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling